// 200 "Did you know?" facts about Miami Beach & EV charging milestones
export const DID_YOU_KNOW_FACTS: string[] = [
  // Miami Beach history & culture
  "Miami Beach was incorporated as a city on March 26, 1915 — making it over 110 years old.",
  "South Beach's Art Deco Historic District is the largest collection of Art Deco architecture in the world.",
  "Miami Beach was originally a mangrove swamp that was dredged and filled starting in 1913.",
  "The famous Ocean Drive strip was built almost entirely between 1930 and 1942.",
  "Miami Beach has more than 800 buildings protected in its historic Art Deco district.",
  "The Art Deco Weekend festival on Ocean Drive draws over 100,000 visitors every January.",
  "Miami Beach's population nearly doubles during tourist season from December through April.",
  "The Venetian Causeway, opened in 1926, was the longest bridge in the world at the time.",
  "Miami Beach's Julia Tuttle Causeway was once home to a famous flamingo colony.",
  "The city of Miami Beach spans 7.1 square miles, about half of which is water.",
  "Miami Beach has over 35 miles of navigable waterways within the city.",
  "South Beach's pastel-colored hotels were originally white — they were painted pastel in the 1980s.",
  "The Fontainebleau hotel, opened in 1954, set the template for the modern luxury resort.",
  "Miami Beach's Lincoln Road Mall was one of the first pedestrian shopping malls in the US (1960).",
  "The Bass Museum of Art in Miami Beach opened in 1964 and is one of Florida's oldest art museums.",
  "Miami Beach's Española Way was designed in the 1920s to evoke a Spanish village.",
  "The Miami Beach Convention Center is one of the largest in the Southeast US at 1.4 million sq ft.",
  "Art Basel Miami Beach, launched in 2002, is the most important art fair in the Americas.",
  "Miami Beach has hosted Super Bowl six times — more than any other city.",
  "The iconic Colony Hotel on Ocean Drive opened in 1935 and starred in the film Scarface.",

  // Miami nature & environment
  "Biscayne Bay, bordering Miami Beach to the west, is home to more than 600 species of fish.",
  "Miami Beach is built on a barrier island separated from Miami by Biscayne Bay.",
  "The city has invested $500 million to raise roads and install pumps to fight sea-level rise.",
  "Miami Beach experiences about 10 sunny days for every one overcast day.",
  "The average temperature in Miami Beach is 77°F (25°C) year-round.",
  "Miami Beach gets about 62 inches of rain per year — most of it in summer afternoon thunderstorms.",
  "Biscayne National Park, just south of Miami, protects the largest marine park in the US.",
  "Miami Beach's beaches are regularly replenished — the city pumps sand from offshore to maintain them.",
  "The Atlantic Ocean water temperature off Miami Beach averages 77°F in winter and 86°F in summer.",
  "Miami Beach has planted over 3,000 new trees in the past decade as part of its climate resilience plan.",
  "The mangroves around Miami Beach absorb more CO₂ per acre than tropical rainforests.",
  "Miami Beach experiences about 250 days of sunshine per year.",
  "Florida has more lightning strikes per square mile than any other US state.",
  "Bottlenose dolphins are regularly spotted swimming in Biscayne Bay year-round.",
  "Miami Beach's dunes are protected habitat for nesting sea turtles from May through October.",

  // Miami Beach records & firsts
  "Miami Beach's first hotel, the Brown's Hotel, opened in 1915 on what is now the location of the Loews.",
  "Miami Beach hosted its first professional boxing match in 1923.",
  "The first air-conditioned building in Miami Beach was the Sears department store, opened in 1951.",
  "Miami International Airport, just 12 miles away, is the busiest US gateway to Latin America.",
  "Miami Beach's Wolfsonian Museum houses one of the world's finest collections of design art (1885–1945).",
  "The Miami Design District, nearby, attracts more luxury retail brands per block than anywhere in the US.",
  "Nikki Beach on South Beach was the world's first beach club, opening in 1998.",

  // EV history & milestones
  "The first electric vehicle was built in 1884 by English inventor Thomas Parker.",
  "By 1900, electric vehicles outsold gasoline cars in the United States.",
  "The first electric taxi service launched in New York City in 1897.",
  "At the 1900 World Exhibition in Paris, 38 of the 40 cars displayed were electric.",
  "The first speeding ticket was issued to an electric cab driver in New York City in 1899.",
  "Camille Jenatzy set the first land speed record over 100 km/h (62 mph) in an electric car in 1899.",
  "General Motors killed off its EV1 electric car in 2003, inspiring the documentary 'Who Killed the Electric Car?'",
  "The Tesla Roadster, launched in 2008, was the first highway-legal all-electric vehicle with Li-ion cells.",
  "The Nissan LEAF, launched in 2010, became the world's best-selling pure EV for many years.",
  "In 2021, global EV sales surpassed 6 million units for the first time.",
  "Norway leads the world in EV adoption — over 80% of new cars sold there are electric.",
  "China is now the world's largest EV market, with over half of all EVs sold globally.",
  "The US crossed 3 million registered EVs in 2023.",
  "Florida has the third-largest EV fleet of any US state.",
  "Miami-Dade County has the most EV registrations in Florida.",

  // EV technology
  "A typical Level 2 charger like ours adds 10–30 miles of range per hour of charging.",
  "Level 1 charging (standard 120V outlet) adds only 3–5 miles of range per hour.",
  "DC Fast Charging (Level 3) can charge most EVs to 80% in 20–45 minutes.",
  "EV batteries last much longer than most people think — often 200,000+ miles with minimal degradation.",
  "Most EV manufacturers warrant their batteries for 8 years or 100,000 miles.",
  "Charging to 80% and unplugging is better for long-term battery health than always topping to 100%.",
  "Cold weather can temporarily reduce an EV's range by up to 40%.",
  "Miami's warm climate is ideal for EV battery health — batteries perform best above 60°F.",
  "Regenerative braking on EVs can recover up to 70% of braking energy back into the battery.",
  "EV brake pads last 2–3× longer than ICE car brakes because of regenerative braking.",
  "The average EV has fewer than 20 moving parts in its powertrain vs. 2,000+ in a gasoline engine.",
  "EV motors are over 90% efficient at converting electricity to motion; gas engines average 20–40%.",
  "The ChargePoint CPF50 (our charger) is designed for shared multi-family housing.",
  "ChargePoint's network is the largest EV charging network in North America.",
  "A full charge on a typical EV costs $2–$5 at home electricity rates vs. $50–$80 to fill a gas tank.",
  "EVs require no oil changes, no spark plugs, no timing belts, and no transmission fluid.",
  "The average EV owner saves about $800–$1,200 per year on fuel compared to a gas vehicle.",
  "EV maintenance costs are 40% lower on average than equivalent gasoline vehicles.",
  "Smart charging (charging during off-peak hours) can cut electricity costs by 30–50%.",
  "Vehicle-to-Grid (V2G) technology allows EVs to power homes during outages.",
  "Some utility companies offer rebates of $500–$1,000 for installing home EV chargers.",
  "The weight of an EV battery pack is typically 800–1,200 lbs — heavier than most engines.",
  "Tesla's Supercharger network has over 50,000 chargers globally as of 2024.",
  "Ford's Mustang Mach-E was named after the most iconic American muscle car.",
  "The Rivian R1T was the first all-electric pickup truck to go on sale in the US (2021).",
  "The Chevy Silverado EV has an estimated 450-mile range — more than most gas trucks.",
  "Porsche's Taycan broke the Nürburgring lap record for EVs at 7 minutes 33 seconds.",
  "The Lucid Air has an EPA-rated range of 516 miles — the longest of any EV ever tested.",
  "Ferrari's first ever EV, the 2024 Ferrari Elettrica, produces 1,326 horsepower.",
  "BMW's iX M60 can accelerate from 0 to 60 mph in 3.6 seconds.",
  "Kia and Hyundai together sell more EVs in the US than any brand except Tesla.",
  "The average American drives 37 miles per day — well within the range of any modern EV.",
  "About 80% of EV charging in the US happens at home overnight.",
  "Public charging availability has grown 40% year-over-year since 2020.",

  // EV environment & energy
  "An EV driving on average US grid electricity produces 50% less CO₂ than a gas car.",
  "In Miami, where Florida Power & Light has significant solar capacity, EVs are even cleaner.",
  "If all US cars were electric, carbon emissions from transportation would drop by 1.5 billion tons/year.",
  "Manufacturing an EV has a larger carbon footprint than making a gas car — but is offset within 1–2 years of driving.",
  "Recycling an EV battery can recover over 95% of its lithium, cobalt, and nickel.",
  "The global EV industry is expected to require 40× more lithium by 2030 than today.",
  "Solar-charged EVs produce near-zero lifetime carbon emissions.",
  "Florida gets more solar energy potential than almost any other US state.",
  "The US electricity grid is getting cleaner every year — making EVs greener over time automatically.",
  "EVs produce zero tailpipe emissions, improving air quality in dense urban areas like Miami Beach.",
  "Urban air quality improvement from EV adoption reduces asthma hospitalizations by measurable amounts.",
  "The noise reduction from EVs vs. gas cars meaningfully reduces urban noise pollution.",

  // Condo living & EV charging
  "Shared EV chargers in condos increase property values by an estimated 3–5%.",
  "Florida law (F.S. 508.110) gives condo residents the right to request EV charging installation.",
  "Miami-Dade County offers rebates up to $500 for multi-family EV charging installations.",
  "ChargePoint's RFID access control means only authorized residents can use our charger.",
  "Level 2 shared chargers in condos typically pay for themselves in 3–5 years through reduced maintenance costs.",
  "Most EV drivers only need to charge 2–4 times per week for typical commuting.",
  "Overnight charging (10pm–6am) typically uses cheaper off-peak electricity rates.",
  "The average EV charges from 20% to 80% in about 2–3 hours on a Level 2 charger.",
  "Coordinating charger use in a condo building is the #1 challenge for shared EV charging.",
  "Apps like 2020EV are part of a growing category of 'smart building' EV management tools.",
  "A ChargePoint CPF50 charger delivers up to 7.2 kW — enough to add ~25 miles of range per hour.",
  "Real-time charger status notifications reduce wait times by an average of 40% in shared settings.",
  "A typical 60 kWh EV battery (enough for ~200 miles) takes about 8 hours to charge from empty on Level 2.",
  "Most EV owners never fully empty the battery — typical daily charging adds 20–40 miles.",

  // Fun EV & tech facts
  "The Tesla Model S Plaid has a 0–60 mph time of 1.99 seconds — faster than most Formula 1 cars off the line.",
  "Amazon has ordered 100,000 electric delivery vans from Rivian for its fleet.",
  "UPS is deploying thousands of electric delivery vehicles starting with Miami and other dense urban routes.",
  "Miami-Dade Transit is converting its entire 800-bus fleet to electric by 2035.",
  "The world's fastest production EV, the Rimac Nevera, does 0–60 in 1.74 seconds.",
  "The first electric school bus in the US was deployed in 2019 in Montgomery County, Maryland.",
  "New York City aims to have all taxis and rideshare vehicles electric by 2030.",
  "Uber has committed to being a fully electric platform in the US, Canada, and Europe by 2030.",
  "Every major automaker has committed to an all-electric or majority-electric lineup by 2035.",
  "The IRS offers a $7,500 federal tax credit for new EV purchases (income limits apply).",
  "Florida offers no state income tax savings on EV purchases, but waives the annual registration fee difference.",
  "The charging cable on a Level 2 EVSE (Electric Vehicle Supply Equipment) carries up to 32 amps.",
  "EV charging stations don't actually store electricity — they control the flow from the grid to your car.",
  "Your EV's onboard charger converts AC power from the wall into DC power for the battery.",
  "DC Fast Chargers bypass the onboard charger and send DC power directly to the battery.",

  // Miami Beach & sustainability
  "Miami Beach declared a climate emergency in 2019 and committed to carbon neutrality by 2050.",
  "The city of Miami Beach installed solar panels on 11 public buildings generating 1.5 MW of power.",
  "Miami Beach's bus rapid transit route (the 'S' line) serves Ocean Drive and Washington Ave.",
  "Citi Bike Miami Beach has over 100 stations and 1,000 bikes for emissions-free local transport.",
  "Miami Beach's electric golf carts, popular in South Beach, have been street-legal since 2005.",
  "Florida Power & Light (FPL) has added 30 million solar panels — the most of any US utility.",
  "FPL plans to eliminate all coal from its power generation mix by 2025.",
  "Miami Beach was one of the first cities in the US to ban single-use plastic straws (2018).",
  "The Miami Beach Botanical Garden is a certified green building and sustainability demonstration site.",
  "Miami Beach's Convention Center received LEED Gold certification after its 2018 renovation.",
  "Miami Beach uses reclaimed water for irrigation, saving 5 million gallons of potable water daily.",
  "The city's electric-powered beach raking vehicles clean 8 miles of shoreline every morning.",
  "Miami Beach's parking garages now have solar canopies, generating power while shading cars.",
  "Electric water taxis operate on Biscayne Bay, offering a scenic emission-free commute.",
  "Miami Beach piloted autonomous electric shuttle buses in 2020 along Lincoln Road.",

  // More Miami Beach fun facts
  "The original name for Miami Beach was 'Alton Beach,' named after developer Alton Beach Road.",
  "The world's first neon signs in the US debuted on Miami Beach's Collins Avenue in the 1940s.",
  "Miami Beach's population is about 82,000 full-time residents but hosts 15 million visitors per year.",
  "There are 27 bridges connecting Miami Beach to the mainland.",
  "Miami Beach has more Rolls-Royces and Lamborghinis per capita than almost any US city.",
  "The original Roney Plaza hotel, once Miami Beach's most glamorous, was demolished in 1968.",
  "Jackie Gleason filmed his TV variety show in Miami Beach from 1964 to 1970.",
  "The Miami Beach Police Department was founded in 1915 — just days after the city's incorporation.",
  "Miami Beach's first mayor was John N. Lummus, who served from 1915 to 1917.",
  "The famous 'pink palace' — the old Versace mansion on Ocean Drive — sold for $41.5 million in 2013.",
  "Miami Beach's annual Ultra Music Festival attracts 170,000 attendees over three days.",
  "The Miami Beach Film Festival, started in 1997, screens over 200 films from 40+ countries each year.",
  "Star Island, accessible only by bridge, is home to some of the priciest real estate in Florida.",
  "Miami Beach's average home price has increased more than 150% since 2020.",
  "The Miami Beach skyline is entirely free of skyscrapers — height limits protect ocean views.",
  "Miami Beach has more restaurants per capita than New York City.",
  "The iconic pink flamingos of Miami Beach are actually not native to Florida — they're from Cuba and the Caribbean.",
  "The Miami Beach Symphony has been performing free concerts in the park since 1953.",
  "South Pointe Park at the tip of Miami Beach offers the best views of cruise ships entering the port.",
  "Miami Beach's Joe's Stone Crab restaurant, opened in 1913, is one of the oldest in Florida.",
];
